### ISSUE TITLE
Self-Hosting Suggester Throw Error As Well As Main Suggester!

### ISSUE THREAD

**Issue by SahilOP69** [Suggester/Suggester#212]
When We do  `.edit <suggest id> <comment>`  it errors in main bot as well as in Self-Hosted The Error Is:
```
ParallelSaveError: Can't save() the same doc multiple times in parallel. Document: 6059e51da077430025b2a361
```
Thanks 👍

**Comment by Suspense4615** [comment]
Hey there, this issue has been fixed in [Suggester v4.10.3](https://suggester.js.org/#/changelogs/changelog-2021?id=suggester-v4103-june-17th-2021) released almost 2 months ago. As a reminder, we do not support selfhosted versions of the bot so if this issue still occurs, you'll either have to fix it on your own or update your fork to be up to date with the official version.
